"""Tabelas iniciais

Revision ID: 2bddf94f09b3
Revises: 
Create Date: 2022-09-01 16:57:59.081949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2bddf94f09b3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("is_winner", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_is_winner"), "movies", ["is_winner"], unique=False)
    op.create_table(
        "producers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "movie_producer",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producers.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "producer_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_producer")
    op.drop_table("producers")
    op.drop_index(op.f("ix_movies_is_winner"), table_name="movies")
    op.drop_table("movies")
    # ### end Alembic commands ###
